# ================================
# Stage 1: Builder
# ================================
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

# ================================
# Stage 2: Production
# ================================
FROM node:22-alpine AS production

WORKDIR /app

COPY package*.json .

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist

EXPOSE 5050

CMD ["npm", "run", "start:prod"]
